### PR TITLE
Small Typo

### PR DESCRIPTION
**Pull request by CCOSTAN**
Just needed a open <

### CODE REVIEW

**Comment by klaasnicolaas** [comment]
Thnx, I'm still waiting for merge, because I still have to figure out how to get this adjustment from the remote to the local without affecting / deleting all my other files. (work normally only from local to remote never the other way around)

**Comment by CCOSTAN** [comment]
No worries.. You can delete and fix by hand if it's easier..  Just thought I'd save ya a step. :)

**Comment by klaasnicolaas** [comment]
But that's why I want to learn it too 😄 I have no idea what a correct way is, to only have the readme file adapted to me local after the merge

**Comment by CCOSTAN** [comment]
I use this command ```git pull origin master``` to pull changes from remote to local.

https://github.com/CCOSTAN/Home-AssistantConfig/blob/master/config/shell_scripts/gitpull.sh#L6

**Comment by klaasnicolaas** [comment]
But does not that cause problems if I have uncommited changes on my local?

**Comment by CCOSTAN** [comment]
Not sure.. Definitely commit your changes first so you don't lose anything.

**Comment by klaasnicolaas** [comment]
To be on the safe side, a test done on another repo of me. It worked fine with `git pull origin master`

**Pull request merged**
